# ----------------------------------------------------------------------------
#
# Package             : reflections
# Source Repo         : https://github.com/ronmamo/reflections
# Travis Job Link     : https://travis-ci.com/github/genisysram/reflections/builds/211997518/config
# Created travis.yml  : No
# Maintainer          : <ramakrishna.s@genisys-group.com>
#                       <sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------


arch:
    - amd64
    - ppc64le
language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk11
